#
# Docker containers
# https://medium:com/@iamfaisalkhatri/parallel-execution-of-tests-using-selenium-grid-4-with-docker-compose-2dc243f4fe8b:
#
version: "3.7"

services:
  selenium-hub:
    image: selenium/hub:4.2.2-20220622
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  selenium-chrome:
    image: selenium/node-chrome:4.2.2-20220622
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    ports:
      - "15900:5900"
      - "7900:7900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_INSTANCES: 10
      SE_NODE_MAX_SESSION: 10
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1200
      # PROXY is added when you are running in the cloud version of testing site.
      # In case of you are using the local testing site, such as: http://{your IP address}:8080, please remove the Proxy.
#      HTTP_PROXY: 'http://dc-ty3-squid-1.cb.local:3128'
#      HTTPS_PROXY: 'http://dc-ty3-squid-1.cb.local:3128'
